### ISSUE TITLE
Swapped Flies

### ISSUE THREAD

**Issue by ghost** [miguelgaspar24/FlyTracker_Fixes#5]
Hi,
I am using flytracker with the multi-fix to get distances and angles between multiple flies at each frame. Flytracker has a feature to correct swapping events, but for some reason when I use this feature (manually swap two flies) the relative features (such as dist-to-other, facing angle, etc...) are not changed, it only re-assigns the data to the new Ids. I was wondering if there is a way to fix this issue.

Thanks.

**Comment by miguelgaspar24** [comment]
Hi,
First of all I am terribly sorry about my lack of response, at the time I was still exploring solutions to this issue, and then I had to leave it hanging for quite some time... You can now find the updated files, which should fix your problem. I have indeed tested identity swapping and now when you save your changes, FlyTracker will change the features accordingly.
I hope this can still be of some use for you or anyone you now who might make use of this. Feel free to report any other issues that I might be able to address.
Thanks!
